name: flutter_spark_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dartz: ^0.10.1
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  get_it: ^8.0.3
  go_router: ^14.6.2
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/config/
    - assets/jsons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/cairo.ttf
flutter_intl:
  enabled: true
